### ISSUE TITLE
foreign arch and sources setup for `build-packages`

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1476]
#1348 [design](https://forum.snapcraft.io/t/multi-arch-build-packages/1678)

**Comment by kalikiana** [comment]
This has been delayed due to the complexity of apt-get build-dep. The original design has been re-worked, good news is, the new plan is much simpler. I'm now planning on landing this in two pieces, informing the user on how to set up the host for multi-arch (#1348) and peforming the equivalent set up for containers automatically (not proposed yet). These should be ready this or next week.
