### ISSUE TITLE
catkin plugin: detect and gracefully handle rosinstall clashes

### ISSUE THREAD

**Issue by sergiusens** [snapcore/snapcraft#1715]
Estimate: 5 days

The Catkin plugin currently supports parsing rosinstall files to pull the various repositories that make up the workspace that it will build. A request from Shadow Robotics is to add the ability to then look inside the pulled workspace for more rosinstall files, and fetch their repositories as well. This is not supported by rosinstall alone. Would be nice if Snapcraft was smart enough to know if rosinstall files clash with each other (e.g. file A requires repo foo, hash 1234, file B requires repo foo hash abcd).

**Comment by kyrofa** [comment]
After looking at the [solutions](https://github.com/shadow-robot/sr-build-tools/blob/master/ansible/roles/ros_workspace/files/load_repositories.sh) vendors are currently using for  recursively fetching rosinstall files, I think this issue is a lot of pain for really no gain. We now support fetching them recursively, I say we cancel this extension unless people explicitly request this functionality.
