### ISSUE TITLE
cross-compilation support for catkin plugin

### ISSUE THREAD

**Issue by Timple** [snapcore/snapcraft#1827]
Relevant piece of config:

```yaml
parts:
  workspace:
    plugin: catkin
    rosdistro: kinetic
```

Output of cross-compilation command
```bash
$ snapcraft --target-arch=armhf 
Setting target machine to 'armhf'
...
NotImplementedError: The plugin used by 'workspace' does not support cross-compiling to a different target architecture
```

**Comment by kyrofa** [comment]
I know this is a tad confusing, but I'm afraid we don't track issues here (the reason you see any issues is because we use the Projects feature). We use [Launchpad](https://bugs.launchpad.net/snapcraft) for bugs/feature requests.

So I'm going to close this here, and feel free to re-log over there, but I'll also briefly respond. Cross-compiling ROS is far more involved than cross-compiling just a simple CMake project. One firsts needs to cross-compile the relevant parts of ROS, and _then_ the desired workspace. This is a large change from the current functionality in the Catkin plugin, which uses the ROS archive. So far it's our recommendation to use the Launchpad builder services to build ARM Catkin snaps. However, if this is something with which you have experience outside of snaps, I'd be interested in chatting to see if we can work together to get support added for it.
